### PR TITLE
Fixing test

### PR DESCRIPTION
**Pull request by hernoufM**
This PR aims to fix and to stabilize current tests

### CODE REVIEW

**Comment by rjbou** [comment]
what is the difference between test 3 & 4 ?

**Comment by rjbou** [comment]
test 3: is there a reason to keep wxs if you don't print them ?

**Comment by hernoufM** [comment]
> what is the difference between test 3 & 4 ?

Ah, actually no difference. I ll remove on of them

**Comment by hernoufM** [comment]
> test 3: is there a reason to keep wxs if you don't print them ?

you are right, i ll remove it also

**Comment by rjbou** [comment]
Tested tests locally, all green

**Pull request merged**
